USE [master]
GO

/****** Object:  Database [CareMyPet]    Script Date: 04/03/2019 18:46:57 ******/
CREATE DATABASE [CareMyPet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CareMyPet', FILENAME = N'C:\Users\USER\CareMyPet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CareMyPet_log', FILENAME = N'C:\Users\USER\CareMyPet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CareMyPet] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CareMyPet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CareMyPet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CareMyPet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CareMyPet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CareMyPet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CareMyPet] SET ARITHABORT OFF 
GO

ALTER DATABASE [CareMyPet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CareMyPet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CareMyPet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CareMyPet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CareMyPet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CareMyPet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CareMyPet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CareMyPet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CareMyPet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CareMyPet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CareMyPet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CareMyPet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CareMyPet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CareMyPet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CareMyPet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CareMyPet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CareMyPet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CareMyPet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CareMyPet] SET  MULTI_USER 
GO

ALTER DATABASE [CareMyPet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CareMyPet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CareMyPet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CareMyPet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CareMyPet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CareMyPet] SET QUERY_STORE = OFF
GO

USE [CareMyPet]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CareMyPet] SET  READ_WRITE 
GO


